name: Milestone Submission
description: To submit a Milestone
title: "[Milestone Submission]: "
labels: ["Milestone Submission"]
projects: ["toposware/topos-builders-program"]
body:
  - type: markdown
    attributes:
      value: |
          **Instructions:**
          This is the first part of a two-part application. Part 1 focuses on the technical aspects of your Milestone submission. Part 2 is a form that confirms you are who you say you are, and triggers the review of your Milestone.
  - type: input
    id: project_title
    attributes:
      label: Project title
      description: Name of your Project
    validations:
      required: true
  - type: input
    id: project_application_link
    attributes:
      label: Link to grant application issue
      description: Please link to the original Grant Application issue you submitted during the application process.
    validations:
      required: true
  - type: textarea
    id: milestone_submission
    attributes:
      label: Milestone submission
      description: Please mirror the information you provided in the summary of your Milestones in your application.
      value: |
        Milestone Number:
        Milestone Summary:
        Milestone Timeframe: 
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ## Milestone Deliverables

        **Important information for Milestone 1**
        To complete the Issue for Milestone 1, you only need to fill in the section 'Link to the open-source code/Delivery' and 'Licence'.  If you can fill in any other fields, it will be appreciated but is not mandatory. Please put n/a in the irrelevant fields.
        
        To submit Milestone 1 you need to have achieved the following:
        Committed high-quality code that is representative of the rest of the project. 
          1. It must be either modified open-source code or created by you. If the code is modified, it must include the relevant licenses for use, modification and publication. The original code in this case must be licensed under APACHE2. 
          2. Code should show that you will be capable of carrying out the project.
          3. This is an indicator of intent and should show that you've begun the project, you do not need to have created anything else.

        **Important information for Milestone 2**

        To complete milestones 2 you must complete the following fields.
        
        Throughout this section, please
          1. Include any information that you think is relevant to the deliverable in each section.
          2. Highlight any deliverables that significantly deviate from your Grant Agreement with a brief explanation of the difference.
  - type: input
    id: repository_link
    attributes:
      label: Link to the open-source code/delivery
      description: Please link to the relevant GitHub repository
  - type: input
    id: repository_license
    attributes:
      label: License
      description: This is expected to be APACHE2 unless otherwise outlined in your Grant Agreement.
  - type: input
    id: repository_documentation
    attributes:
      label: Documentation
      description: Ideally any documentation will be part of the relevant GitHub repository. Please put a link here.  If not, please link to another public source (e.g. an open-access Google Doc)
  - type: markdown
    attributes:
      value: |
        As this is a project on a testnet, you are not expected to create extensive documentation. However, you will need to create sufficient documentation to allow the grant committee to assess your project.

        Where applicable please document the areas below. Do not write detailed explanations of already existing components.

        * API calls
        * Architecture overview and individual component details
        * Algorithms and protocols that are core to your project
        * Any other fundamental building blocks to your technology
  - type: textarea
    id: further_documentation
    attributes:
      label: Further documentation
  - type: input
    id: repository_tests
    attributes:
      label: Tests for critical functions
      description: Ideally will be part of the relevant GitHub repository. Please put a link here. If not, please link to another public source. See the section "Testing Guide" in the [Milestone Guide](https://github.com/toposware/topos-builders-program/blob/main/milestone_guide.md) for further information.
  - type: textarea
    id: other_deliverables
    attributes:
      label: Other milestone deliverables
      description: If appropriate please include any other deliverables for this Milestone that you included in your application.
  - type: textarea
    id: additional_info
    attributes:
      label: Any additional information
      description: Please include any information you think would be useful to allow Toposware to assess your Milestone submission.
  - type: markdown
    attributes:
      value: |
        ***
        Once you have submitted this issue, please fill in the form found [here](http://buildersprogram.toposware.com/milestonesform).


